name: 'Ordinary Nix Cache'
description: 'Caches build results in the github actions cache.'
branding:
  icon: "box"
  color: "blue"
inputs: {}
outputs: {}
runs:
  using: 'node20'
  main: 'dist/index.mjs'
  post: 'dist/index.mjs'
