on: [push]

jobs:
  first-build:
    runs-on: ubuntu-latest
    name: First build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Cache
        uses: ./
      - name: Nix build
        run: nix-build --expr 'derivation { name = "dummy"; builder = "/bin/sh"; system = builtins.currentSystem;  args = ["-c" "echo ${{github.sha}} > $out"];}'

  second-build:
    runs-on: ubuntu-latest
    name: Second build
    needs: first-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Cache
        uses: ./
      - name: Nix build
        run: nix-build --max-jobs 0 --expr 'derivation { name = "dummy"; builder = "/bin/sh"; system = builtins.currentSystem;  args = ["-c" "echo ${{github.sha}} > $out"];}'
